export const APPS_VIEW_QUERY_KEY = 'view';
export const APPS_VIEW_QUERY_VALUE = 'apps';
export const APPS_RESTORE_STORAGE_KEY = 'bolt_apps_restore';
export const COMPOSIO_GUEST_ID_STORAGE_KEY = 'bolt_composio_guest_id';

export const APPROVED_APP_CONNECTOR_NAMES = [
  'Stripe',
  'Salesforce',
  'Slack',
  'Notion',
  'Google Calendar',
  'Google Drive',
  'Gmail',
  'Google Sheets',
  'Google Slides',
  'Google Docs',
  'Google BigQuery',
  'Google Tasks',
  'Google Meet',
  'HubSpot',
  'LinkedIn',
  'TikTok',
  'Discord',
  'GitHub',
  'GitLab',
  'Box',
  'ClickUp',
  'Google Analytics',
  'Outlook',
  'Linear',
  'Dropbox',
  'Google Search Console',
  'Google Classroom',
  'Airtable',
  'Microsoft Teams',
  'Microsoft SharePoint',
  'Microsoft OneDrive',
  'Typeform',
  'Hugging Face',
  'Calendly',
  'Contentful',
  'Supabase',
  'Gong',
  'Ramp',
  'Facebook',
  'DocuSign',
  'Apollo',
  'RocketLane',
  'Telegram',
  'YouTube',
  'Excel',
  'Hackernews',
  'Zendesk',
  'Confluence',
  'Instagram',
  'PostHog',
  'Vercel',
  'Snowflake',
  'Zoho CRM',
  'Monday',
  'Pipedrive',
] as const;

const APPROVED_APP_CONNECTOR_SLUGS = [
  'stripe',
  'salesforce',
  'slack',
  'notion',
  'googlecalendar',
  'googledrive',
  'gmail',
  'googlesheets',
  'googleslides',
  'googledocs',
  'googlebigquery',
  'googletasks',
  'googlemeet',
  'hubspot',
  'linkedin',
  'tiktok',
  'discord',
  'github',
  'gitlab',
  'box',
  'clickup',
  'googleanalytics',
  'outlook',
  'linear',
  'dropbox',
  'googlesearchconsole',
  'googleclassroom',
  'airtable',
  'microsoftteams',
  'microsoftsharepoint',
  'microsoftonedrive',
  'typeform',
  'huggingface',
  'calendly',
  'contentful',
  'supabase',
  'gong',
  'ramp',
  'facebook',
  'docusign',
  'apollo',
  'rocketlane',
  'telegram',
  'youtube',
  'excel',
  'hackernews',
  'zendesk',
  'confluence',
  'instagram',
  'posthog',
  'vercel',
  'snowflake',
  'zohocrm',
  'monday',
  'pipedrive',
] as const;

const APPROVED_APP_CONNECTOR_ALIASES = [
  'googlebigquery',
  'googleanalytics',
  'googlesearchconsole',
  'googleclassroom',
  'googledrive',
  'googlecalendar',
  'googlesheets',
  'googleslides',
  'googledocs',
  'googletasks',
  'googlemeet',
  'microsoftteams',
  'microsoftsharepoint',
  'microsoftonedrive',
  'zohocrm',
  'huggingface',
  'docusign',
  'clickup',
  'rocketlane',
  'posthog',
  'hackernews',
] as const;

export function normalizeAppConnectorKey(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '');
}

const approvedAppConnectorKeys = new Set([
  ...APPROVED_APP_CONNECTOR_NAMES.map(normalizeAppConnectorKey),
  ...APPROVED_APP_CONNECTOR_SLUGS.map(normalizeAppConnectorKey),
  ...APPROVED_APP_CONNECTOR_ALIASES.map(normalizeAppConnectorKey),
]);

export function isApprovedAppToolkit(toolkit: { slug?: string; name?: string }) {
  return [toolkit.slug, toolkit.name].some((value) => {
    if (!value) {
      return false;
    }

    return approvedAppConnectorKeys.has(normalizeAppConnectorKey(value));
  });
}
