export const OPENAI_PROVIDER_NAME = 'OpenAI';
export const GOOGLE_PROVIDER_NAME = 'Google';
export const DEFAULT_LLM_PROVIDER_NAME = OPENAI_PROVIDER_NAME;
export const DEFAULT_OPENAI_MODEL = 'gpt-5.4';
export const OPENAI_SERVER_API_KEY = 'OPENAI_API_KEY';
export const GOOGLE_SERVER_API_KEY = 'GOOGLE_GENERATIVE_AI_API_KEY';

export const SERVER_MANAGED_PROVIDER_NAMES = new Set([OPENAI_PROVIDER_NAME, GOOGLE_PROVIDER_NAME]);
